services:
  qdrant:
    image: qdrant/qdrant:v1.15.0
    container_name: constraint-monitor-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      # Uses bash's /dev/tcp feature to make HTTP request (no curl/wget needed)
      # Must explicitly call bash since CMD-SHELL defaults to sh
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/6333 && echo -e 'GET / HTTP/1.0\\r\\n\\r\\n' >&3 && timeout 1 grep -q '200 OK' <&3"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: constraint-monitor-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  qdrant-data:
    driver: local
  redis-data:
    driver: local

networks:
  default:
    name: constraint-monitor-network